PHYSICS_TOPICS = [
    {"id": 1, "name": "Kinematyka, wektory"},
    {"id": 2, "name": "Dynamika - siły, praca, moc, energia"},
    {"id": 3, "name": "Rzuty w polu grawitacyjnym"},
    {"id": 4, "name": "Pęd. Zasada zachowania pędu"},
    {"id": 5, "name": "Ruch jednostajny po okręgu"},
    {"id": 6, "name": "Ruch obrotowy bryły sztywnej, moment siły"},
    {"id": 7, "name": "Pole grawitacyjne"},
    {"id": 8, "name": "Hydrostatyka (także prawo Archimedesa w gazach)"},
    {"id": 9, "name": "Gazy"},
    {"id": 10, "name": "Termodynamika"},
    {"id": 11, "name": "Elektrostatyka"},
    {"id": 12, "name": "Prąd stały"},
    {"id": 13, "name": "Magnetyzm"},
    {"id": 14, "name": "Indukcja elektromagnetyczna"},
    {"id": 15, "name": "Prąd zmienny"},
    {"id": 16, "name": "Drgania. Sprężystość ciał"},
    {"id": 17, "name": "Fale mechaniczne"},
    {"id": 18, "name": "Akustyka"},
    {"id": 19, "name": "Optyka geometryczna"},
    {"id": 20, "name": "Optyka fizyczna. Fale elektromagnetyczne"},
    {"id": 21, "name": "Atom wodoru"},
    {"id": 22, "name": "Zjawisko fotoelektryczne. Dualizm korp. - falowy"},
    {"id": 23, "name": "Fizyka jądrowa"},
    {"id": 24, "name": "Teoria względności"},
    {"id": 25, "name": "Astronomia"},
    {"id": 26, "name": "Inne"}
] 